language: scala

jdk: oraclejdk8

env:
  global:
    - sbtDistVersionOverride="-Dproject.version=2.12.4"
    - version=2.12.4

script:
  - scripts/jobs/release/smoketest

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
