#!/bin/bash -ex

scriptDir="$( cd "$( dirname "$0" )" && pwd )"

function latestNightly() {
  >&2 echo "No Scala version specified. Using latest nightly."
  url='https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/lastSuccessfulBuild/artifact/jenkins.properties/*view*/'
  curl -f -s -L $url | grep ^version= | cut -d= -f2
}

export version=${version-`latestNightly`}
echo "Scala version:" $version

rm -rf $scriptDir/ivy2

integrationRepoUrl="https://scala-ci.typesafe.com/artifactory/scala-integration/"
sonatypeStagingUrl="https://oss.sonatype.org/content/repositories/staging/"

sbt \
  -Dsbt.log.noformat=true \
  -Dsbt.ivy.home=$scriptDir/ivy2 \
  -Dproject.version=$version \
  "set resolvers ++= List(\"scala-integration\" at \"$integrationRepoUrl\", \"sonatype-staging\" at \"$sonatypeStagingUrl\")" \
  clean run
