#!/bin/bash -ex

scriptDir="$( cd "$( dirname "$0" )" && pwd )"

function latestNightly() {
  >&2 echo "No Scala version specified. Using latest nightly."
  url='https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/lastSuccessfulBuild/artifact/jenkins.properties/*view*/'
  curl -f -s -L $url | grep ^version= | cut -d= -f2
}

export version=${version-`latestNightly`}
echo "Scala version:" $version

rm -rf $scriptDir/ivy2

sbt \
  -Dsbt.log.noformat=true \
  -Dsbt.ivy.home=$scriptDir/ivy2 \
  -Dsbt.override.build.repos=true \
  -Dsbt.repository.config=repositories \
  -Dproject.version=$version \
  clean run
