#!/bin/bash -ex

scriptDir="$( cd "$( dirname "$0" )" && pwd )"

# put some recent nightly from https://scala-webapps.epfl.ch/jenkins/view/scala-release-2.11.x/job/scala-release-2.11.x/
version=2.11.2-854de2d-nightly
repositoriesFile=$scriptDir/../jenkins-scripts/repositories-scala-release

[[ -e $repositoriesFile ]] || {
  echo "repos file does not exist $repositoriesFile"
  exit 1
}

cat $repositoriesFile

rm -rf $scriptDir/ivy2

sbt \
  -Dsbt.log.noformat=true \
  -Dsbt.ivy.home=$scriptDir/ivy2 \
  -Dsbt.override.build.repos=true \
  -Dsbt.repository.config=$repositoriesFile \
  -Dproject.version=$version \
  clean run
